-- ============================================================
-- 003_blog_posts.sql
-- Blog post drafts generated by the SEO agent
-- ============================================================

CREATE TABLE IF NOT EXISTS blog_posts (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    target_keyword  TEXT NOT NULL,
    title           TEXT NOT NULL,
    slug            TEXT NOT NULL UNIQUE,
    mdx_content     TEXT NOT NULL,
    h2_outline      TEXT[],
    word_count      INTEGER,
    status          TEXT NOT NULL DEFAULT 'draft',
                    -- 'draft' | 'approved' | 'rejected' | 'published'
    pr_url          TEXT,
    rejection_note  TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
